Resources:

  # Based off the cloudformation template output of serverless-plugin-aws-alerts
  AppSyncServerErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      Namespace: ${self:provider.stackName}
      MetricName: AppSyncServerErrors
      Threshold: 1
      Period: 60
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - !Ref AwsAlertsAlarm
      TreatMissingData: missing
      Statistic: Sum

  SMSSpendLimitErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      Namespace: ${self:provider.stackName}
      MetricName: SMSSpendLimitErrors
      Threshold: 1
      Period: 60
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - !Ref AwsAlertsAlarm
      TreatMissingData: missing
      Statistic: Sum
