name: Continuous Integration
on: [push]
jobs:

  real-auth-pytest:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: us-east-1

    steps:
    - name: Git checkout
      uses: actions/checkout@v1

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install Poetry
      uses: dschep/install-poetry-action@v1.3

    - name: Install dependencies
      run: cd real-auth && poetry install

    - name: Test with pytest
      run: cd real-auth && poetry run pytest tests

  real-main-pytest:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: us-east-1

    steps:
    - name: Git checkout
      uses: actions/checkout@v1

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install Poetry
      uses: dschep/install-poetry-action@v1.3

    - name: Install dependencies
      run: cd real-main && poetry install

    - name: Test with pytest
      run: cd real-main && poetry run pytest -n auto app_tests migrations_tests

  flake8:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v1

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install flake8==3.8.0a2  # alpha for walrus operator support

    - name: Lint real-auth with flake8
      run: |
        flake8 real-auth/real_auth real-auth/tests

    - name: Lint real-main with flake8
      run: |
        flake8 real-main/app real-main/app_tests real-main/migrations real-main/migrations_tests

    - name: Lint real-cloudfornt with flake8
      run: |
        flake8 real-cloudfront/edge_app

  eslint:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v1

    - name: Set up Node 12.X
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install dependencies
      run: |
        npm --prefix integration-testing install eslint

    - name: Lint with eslint
      run: |
        npm --prefix integration-testing run lint
